### ISSUE TITLE
crates.io repo link typo

### ISSUE THREAD

**Issue by yurkobb** [FineFindus/udisks-rs#1]
Hi! Thanks for the crate! Just letting you know [the crates.io page](https://crates.io/crates/udisks2) links to a 404 on github (`.../udisk-rs` instead of `.../udisks-rs`).

**Comment by FineFindus** [comment]
Thanks for catching it, I have a tendency to skip the 's' :)
Fixed it, though I don't think it will show up on crates.io until the next release, which is still a while away.
