### ISSUE TITLE
Pure Rust implementation of GIcon

### ISSUE THREAD

**Issue by bilelmoussaoui** [FineFindus/udisks-rs#3]
Hey, I think you can replace the gio feature with https://github.com/bilelmoussaoui/ashpd/blob/master/src/desktop/icon.rs

**Comment by FineFindus** [comment]
Thanks, but reading through the code it doesn't seem like `Icon` has a way of actually getting the `gio::ThemedIcon`?

**Comment by bilelmoussaoui** [comment]
what do you mean by that? `gio::ThemedIcon` is basically `Icon::Names(Vec<String>)`

**Comment by bilelmoussaoui** [comment]
The major difference is the lack of automatically fallback between -symbolic and the "normal" icon

**Comment by FineFindus** [comment]
Oh, I must have looked at the wrong doc :(. Thanks for pointing out the difference, in that case `gio` can indeed be removed, as we only ever return a single icon/symbolic icon name.
