### ISSUE TITLE
[Question] Updating crate?

### ISSUE THREAD

**Issue by jojo2357** [FineFindus/udisks-rs#5]
Hello, the current available crate is 8 months old but there are much newer commits, are there plans to update it?

I would like to use it for [this project](https://gitlab.com/mission-center-devs/mission-center) without rewriting everything if possible.

**Comment by FineFindus** [comment]
Sure, https://crates.io/crates/udisks2/0.2.0. However, there will be more breaking changes in the future (this is why there wasn't a new release yet), for e.g. more Rust-idiomatic types.

You can also use it with a git commit, it's what we do in [GNOME Disks](https://gitlab.gnome.org/GNOME/gnome-disk-utility/-/blob/11a68cb45073570487bd2ce92570064194e1cb95/Cargo.toml#L15) currently. Feel free to ping me in the MR, happy to take a look/give feedback :)

**Comment by jojo2357** [comment]
Thanks!

while I'm here i want to ask if it would be possible to make the crate synchronous since that would fit nicely into our project, or if there are ways to use it in a synchronous context.

**Comment by FineFindus** [comment]
It's not planned to provide a synchronous version, as that would mean essentially writing and maintaining two crates at once. As with any async crate you can use [blocking methods](https://docs.rs/glib/latest/glib/struct.MainContext.html#method.block_on) of an async executor to run async code.

**Comment by jojo2357** [comment]
Oh that will work i think, thanks!
